# Generated by Django 4.1.13 on 2024-04-20 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('payment_details', models.JSONField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('preparing', 'Preparing for Shipment'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('completed', 'Order Complete')], default='paid', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
