# Generated by Django 4.1.13 on 2024-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_method',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
